# Generated by Django 4.2.7 on 2026-04-24 09:54

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConnectionName', models.CharField(max_length=100, unique=True)),
                ('HostName', models.CharField(max_length=255)),
                ('Port', models.IntegerField(default=389)),
                ('BaseDN', models.CharField(max_length=255)),
                ('BindDN', models.CharField(blank=True, max_length=255)),
                ('BindPassword', models.CharField(blank=True, max_length=255)),
                ('UserSearchBase', models.CharField(blank=True, max_length=255)),
                ('UserSearchFilter', models.CharField(default='(uid=%(user)s)', max_length=255)),
                ('UseSSL', models.BooleanField(default=False)),
                ('UseTLS', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LDAP Configuration',
                'verbose_name_plural': 'LDAP Configurations',
            },
        ),
        migrations.CreateModel(
            name='WebLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=150, unique=True)),
                ('UserName', models.CharField(max_length=255)),
                ('Pwd', models.CharField(max_length=255)),
                ('AuthMode', models.CharField(choices=[('GTI', 'LDAP (GTI)'), ('INTERNAL', 'Internal')], default='GTI', max_length=20)),
                ('Active', models.BooleanField(default=True)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Department', models.CharField(blank=True, max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('LastLogin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Web Login',
                'verbose_name_plural': 'Web Logins',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('away', 'Away'), ('busy', 'Busy')], default='offline', max_length=20)),
                ('status_message', models.CharField(blank=True, max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_ldap_user', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
