# Generated by Django 4.2.7 on 2026-05-08 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_helpdeskrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskContainer',
            fields=[
                ('container_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('took_over', 'Took Over'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('problem_description', models.TextField()),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='helpdesk_files/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_containers', to='messaging.conversation')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_containers', to=settings.AUTH_USER_MODEL)),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Desk Container',
                'verbose_name_plural': 'Help Desk Containers',
                'ordering': ['-created_at'],
            },
        ),
    ]
