# Generated by Django 4.2.7 on 2026-05-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_helpdeskcontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskcontainer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
