# Generated by Django 4.2.7 on 2026-05-15 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0006_helpdeskcontainer_completion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='messaging.helpdeskcontainer')),
            ],
            options={
                'verbose_name': 'Task Chat Message',
                'verbose_name_plural': 'Task Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
