# Generated by Django 4.2.7 on 2026-05-15 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0007_taskchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_chat_read_states', to='messaging.helpdeskcontainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_chat_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Chat Read State',
                'verbose_name_plural': 'Task Chat Read States',
                'ordering': ['-updated_at'],
                'unique_together': {('task', 'user')},
            },
        ),
    ]
