# Generated by Codex on 2026-05-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0008_taskchat_read_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITMembershipChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by_user_pk', models.IntegerField(blank=True, null=True)),
                ('changed_by_username', models.CharField(max_length=150)),
                ('changed_by_full_name', models.CharField(blank=True, max_length=255)),
                ('target_user_pk', models.IntegerField(blank=True, null=True)),
                ('target_username', models.CharField(max_length=150)),
                ('target_full_name', models.CharField(blank=True, max_length=255)),
                ('from_role', models.CharField(max_length=50)),
                ('to_role', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('normal_to_it', 'Normal user to IT member'), ('it_to_normal', 'IT member to normal user')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_membership_changes_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_membership_changes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IT Membership Change Log',
                'verbose_name_plural': 'IT Membership Change Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
