# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_itmembershipchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='original_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='compressed_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='was_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskcontainer',
            name='file_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='helpdeskcontainer',
            name='original_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskcontainer',
            name='compressed_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskcontainer',
            name='was_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
